In [2]:
import numpy as np
import open3d as o3d
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import laspy
from IPython.display import Image

In [50]:
# data is las
las = laspy.read("data/points2.las")
point_data = np.vstack((las.X, las.Y, las.Z)).transpose()
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(point_data)

In [51]:
o3d.visualization.draw_geometries([pcd])

In [4]:
Image(url="points2.png", width=500, height=300)

In [83]:
# KITTI Dataset
# Load binary point cloud
bin_pcd = np.fromfile("data/007480.bin", dtype=np.float32)

# Reshape and drop reflection values
points = bin_pcd.reshape((-1, 4))[:, 0:3]

# Convert to Open3D point cloud
o3d_pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(points))

# Save to whatever format you like
o3d.io.write_point_cloud("data/007480.pcd", o3d_pcd)

True

In [93]:
pcd = o3d.io.read_point_cloud("data/007480.pcd")

In [94]:
print(np.asarray([pcd.points]))

[[[67.82900238 13.75300026  2.54900002]
  [76.86000061 15.84000015  2.86299992]
  [67.38500214 13.99400043  2.53600001]
  ...
  [ 3.79399991 -1.42900002 -1.77499998]
  [ 4.04500008 -1.50999999 -1.89699996]
  [ 3.81500006 -1.40900004 -1.77999997]]]


In [95]:
# CHALLENGE 2 - VOXEL GRID DOWNSAMPLING 

print(f"Points before downsampling: {len(pcd.points)} ") 
# Random down-sampling:
random_pcd = pcd.random_down_sample(sampling_ratio=0.005)

# Uniform down-sampling:
uniform_pcd = pcd.uniform_down_sample(every_k_points=200)

# Voxel down-sampling:
voxel_pcd = pcd.voxel_down_sample(voxel_size=0.1)

print(f"Points after downsampling: {len(random_pcd.points)}")
print(f"Points after downsampling: {len(uniform_pcd.points)}")
print(f"Points after downsampling: {len(voxel_pcd.points)}")

# DOWNSAMPLING 
# o3d.visualization.draw_geometries((downpcd)) 

Points before downsampling: 110736 
Points after downsampling: 553
Points after downsampling: 554
Points after downsampling: 55288


In [96]:
#CHALLENGE 3 - SEGMENTATION

# Perform plane segmentation on the point cloud 'pcd' using the PCL library
# Random Sample Consensus (RANSAC) algorithm to estimate a plane model within the point cloud.
_, inliers = pcd.segment_plane(distance_threshold=0.3, ransac_n=3, num_iterations=250)

# Extract the inlier points from the original point cloud 'pcd'
inlier_cloud = pcd.select_by_index(inliers)

# Select the outlier points by inverting the inlier indices
outlier_cloud = pcd.select_by_index(inliers, invert=True)

# Color the inlier points red
inlier_cloud.paint_uniform_color([1, 0, 0])

# Color the outlier points blue
outlier_cloud.paint_uniform_color([0, 0, 1])

# Visualize the inlier and outlier point clouds
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])

In [97]:
# CHALLENGE 4 - CLUSTERING USING DBSCAN 
# Perform DBSCAN clustering on the outlier point cloud 'outlier_cloud'
with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm: 
    labels = np.array(outlier_cloud.cluster_dbscan(eps=0.5, min_points=5, print_progress=True)) 

# Determine the maximum label value (number of clusters)
max_label = labels.max() 

# Print the number of clusters in the point cloud
print(f"point cloud has {max_label + 1} clusters") 

# Assign colors to the points based on the cluster labels
colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1)) 

# Set color to 0 (black) for points labeled as noise (-1)
colors[labels < 0] = 0 

# Assign colors to the outlier points in the point cloud
outlier_cloud.colors = o3d.utility.Vector3dVector(colors[:, :3]) 

# Visualize the point cloud with colored clusters
o3d.visualization.draw_geometries([outlier_cloud])

[Open3D DEBUG] Precompute neighbors.
Precompute neighbors.[================>                       ] 37%                                    ] 5%
[Open3D DEBUG] Compute Clusters
Precompute neighbors.[========[Open3D DEBUG] Done Compute Clusters: 466
point cloud has 466 clusters
Precompute neighbors.[========================================] 100%


In [98]:
# BONUS CHALLENGE - CLUSTERING USING KDTREE AND KNN INSTEAD
# Create a KDTree from the outlier point cloud 'outlier_cloud'
pcd_tree = o3d.geometry.KDTreeFlann(outlier_cloud)

# Paint the 15th point in the outlier cloud red
print("Paint the 15th point red.")
outlier_cloud.colors[15] = [1, 0, 0]

# Find the 20 nearest neighbors of the 15th point and paint them blue
print("Find its 20 nearest neighbors, paint blue.")
[k, idx, _] = pcd_tree.search_knn_vector_3d(outlier_cloud.points[15], 20)
np.asarray(outlier_cloud.colors)[idx[1:], :] = [0, 0, 1]

# Visualize the outlier point cloud with colored points
o3d.visualization.draw_geometries([outlier_cloud])

Paint the 15th point red.
Find its 20 nearest neighbors, paint blue.


In [99]:
# CHALLENGE 5 - BOUNDING BOXES IN 3D

# Initialize an empty list to store the oriented bounding boxes (OBBs)
obbs = []

# Group the indices based on the cluster labels
indexes = pd.Series(range(len(labels))).groupby(labels, sort=False).apply(list).tolist()

In [100]:
Max_Points = 1000
Min_Points = 20
clusters = []

# Iterate through the grouped indices
for i in range(0, len(indexes)):
    # Get the number of points in the current cluster
    nb_pts = len(outlier_cloud.select_by_index(indexes[i]).points)
    
    # Check if the number of points falls within the desired range
    if nb_pts > Min_Points and nb_pts < Max_Points:
        # Select the points corresponding to the current cluster
        sub_cloud = outlier_cloud.select_by_index(indexes[i])
        
        # Compute the axis-aligned bounding box (AABB) for the cluster
        obb = sub_cloud.get_axis_aligned_bounding_box()
        
        # Set the color of the bounding box to blue
        obb.color = (0, 0, 1)
        
        # Append the bounding box to the list of OBBs
        obbs.append(obb)

In [101]:
list_of_visuals = []
list_of_visuals.append(outlier_cloud)
list_of_visuals.extend(obbs)
list_of_visuals.append(inlier_cloud)
o3d.visualization.draw_geometries(list_of_visuals)

In [5]:
Image(url="objectdetection.png", width=500, height=300)